extern u64 gzombieskel_BodyZombie_ci4[];
extern u64 gzombieskel_BodyZombie_pal_rgba16[];
extern u64 gzombieskel_Legs_ci4[];
extern u64 gzombieskel_Legs_pal_rgba16[];
extern u64 gzombieskel_HeadZombei_ci4[];
extern u64 gzombieskel_HeadZombei_pal_rgba16[];
extern u64 gzombieskel_HandsZombie_ci4[];
extern u64 gzombieskel_HandsZombie_pal_rgba16[];
extern Vtx gzombieskel_Abdomen_mesh_layer_Opaque_vtx_0[12];
extern Gfx gzombieskel_Abdomen_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Chest_mesh_layer_Opaque_vtx_0[31];
extern Gfx gzombieskel_Chest_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Neck_mesh_layer_Opaque_vtx_0[16];
extern Gfx gzombieskel_Neck_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Neck_mesh_layer_Opaque_vtx_1[8];
extern Gfx gzombieskel_Neck_mesh_layer_Opaque_tri_1[];
extern Vtx gzombieskel_Head_mesh_layer_Opaque_vtx_0[29];
extern Gfx gzombieskel_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Jaw_mesh_layer_Opaque_vtx_0[11];
extern Gfx gzombieskel_Jaw_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Shoulder_l_mesh_layer_Opaque_vtx_0[13];
extern Gfx gzombieskel_Shoulder_l_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Arm_l_mesh_layer_Opaque_vtx_0[11];
extern Gfx gzombieskel_Arm_l_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Hand_l_mesh_layer_Opaque_vtx_0[13];
extern Gfx gzombieskel_Hand_l_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_shoulder_r_mesh_layer_Opaque_vtx_0[13];
extern Gfx gzombieskel_shoulder_r_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_shoulder_r_mesh_layer_Opaque_vtx_1[4];
extern Gfx gzombieskel_shoulder_r_mesh_layer_Opaque_tri_1[];
extern Vtx gzombieskel_arm_r_mesh_layer_Opaque_vtx_0[11];
extern Gfx gzombieskel_arm_r_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_hand_r_mesh_layer_Opaque_vtx_0[13];
extern Gfx gzombieskel_hand_r_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Leg_l_mesh_layer_Opaque_vtx_0[25];
extern Gfx gzombieskel_Leg_l_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Shin_l_mesh_layer_Opaque_vtx_0[22];
extern Gfx gzombieskel_Shin_l_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Foot_l_mesh_layer_Opaque_vtx_0[16];
extern Gfx gzombieskel_Foot_l_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Leg_r_mesh_layer_Opaque_vtx_0[35];
extern Gfx gzombieskel_Leg_r_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Shin_r_mesh_layer_Opaque_vtx_0[24];
extern Gfx gzombieskel_Shin_r_mesh_layer_Opaque_tri_0[];
extern Vtx gzombieskel_Foot_r_mesh_layer_Opaque_vtx_0[16];
extern Gfx gzombieskel_Foot_r_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gzombieskel_f3dlite_material_011_layerOpaque[];
extern Gfx mat_gzombieskel_f3dlite_material_009_layerOpaque[];
extern Gfx mat_gzombieskel_f3dlite_material_010_layerOpaque[];
extern Gfx mat_gzombieskel_f3dlite_material_012_layerOpaque[];
extern Gfx gzombieskel_Root_mesh_layer_Opaque[];
extern Gfx gzombieskel_Abdomen_mesh_layer_Opaque[];
extern Gfx gzombieskel_Chest_mesh_layer_Opaque[];
extern Gfx gzombieskel_Neck_mesh_layer_Opaque[];
extern Gfx gzombieskel_Head_mesh_layer_Opaque[];
extern Gfx gzombieskel_Jaw_mesh_layer_Opaque[];
extern Gfx gzombieskel_Shoulder_l_mesh_layer_Opaque[];
extern Gfx gzombieskel_Arm_l_mesh_layer_Opaque[];
extern Gfx gzombieskel_Hand_l_mesh_layer_Opaque[];
extern Gfx gzombieskel_shoulder_r_mesh_layer_Opaque[];
extern Gfx gzombieskel_arm_r_mesh_layer_Opaque[];
extern Gfx gzombieskel_hand_r_mesh_layer_Opaque[];
extern Gfx gzombieskel_Leg_l_mesh_layer_Opaque[];
extern Gfx gzombieskel_Shin_l_mesh_layer_Opaque[];
extern Gfx gzombieskel_Foot_l_mesh_layer_Opaque[];
extern Gfx gzombieskel_Leg_r_mesh_layer_Opaque[];
extern Gfx gzombieskel_Shin_r_mesh_layer_Opaque[];
extern Gfx gzombieskel_Foot_r_mesh_layer_Opaque[];
extern FlexSkeletonHeader gzombieskel;
#define GZOMBIESKEL_ROOT_POS_LIMB 0
#define GZOMBIESKEL_ROOT_ROT_LIMB 1
#define GZOMBIESKEL_ABDOMEN_LIMB 2
#define GZOMBIESKEL_CHEST_LIMB 3
#define GZOMBIESKEL_NECK_LIMB 4
#define GZOMBIESKEL_HEAD_LIMB 5
#define GZOMBIESKEL_JAW_LIMB 6
#define GZOMBIESKEL_SHOULDER_L_LIMB 7
#define GZOMBIESKEL_ARM_L_LIMB 8
#define GZOMBIESKEL_HAND_L_LIMB 9
#define GZOMBIESKEL_SHOULDER_R_LIMB 10
#define GZOMBIESKEL_ARM_R_LIMB 11
#define GZOMBIESKEL_HAND_R_LIMB 12
#define GZOMBIESKEL_LEG_L_LIMB 13
#define GZOMBIESKEL_SHIN_L_LIMB 14
#define GZOMBIESKEL_FOOT_L_LIMB 15
#define GZOMBIESKEL_LEG_R_LIMB 16
#define GZOMBIESKEL_SHIN_R_LIMB 17
#define GZOMBIESKEL_FOOT_R_LIMB 18
#define GZOMBIESKEL_NUM_LIMBS 19
