extern u64 gWereCit3_CASTLEVANIA2_363D160E_2_0_06AB74FC_ciByRGBAAltered_ci4[];
extern u64 gWereCit3_CASTLEVANIA2_363D160E_2_0_06AB74FC_ciByRGBAAltered_pal_rgba16[];
extern u64 gWereCit3_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_ci4[];
extern u64 gWereCit3_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_pal_rgba16[];
extern u64 gWereCit3_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_ci4[];
extern u64 gWereCit3_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_pal_rgba16[];
extern u64 gWereCit3_uppermouth_i4[];
extern u64 gWereCit3_organ_ci4[];
extern u64 gWereCit3_organ_pal_rgba16[];
extern u64 gWereCit3_furcutout_ia8[];
extern u64 gWereCit3_CASTLEVANIA2_EEAB02A5_2_0_5D4AEAF5_ciByRGBA_ci4[];
extern u64 gWereCit3_CASTLEVANIA2_EEAB02A5_2_0_5D4AEAF5_ciByRGBA_pal_rgba16[];
extern u64 gWereCit3_CASTLEVANIA2_239291CB_2_0_10296851_ciByRGBA_ci4[];
extern u64 gWereCit3_CASTLEVANIA2_239291CB_2_0_10296851_ciByRGBA_pal_rgba16[];
extern u64 gWereCit3_CASTLEVANIA2_CD671B29_2_0_CB4C8B0E_ciByRGBA_ci4[];
extern u64 gWereCit3_CASTLEVANIA2_CD671B29_2_0_CB4C8B0E_ciByRGBA_pal_rgba16[];
extern u64 gWereCit3_CASTLEVANIA2_0B423B84_2_0_E485EF34_ciByRGBA_ci4[];
extern u64 gWereCit3_CASTLEVANIA2_0B423B84_2_0_E485EF34_ciByRGBA_pal_rgba16[];
extern u64 gWereCit3_boot_side_ci8_png_001_ci8[];
extern u64 gWereCit3_boot_side_ci8_png_001_pal_rgba16[];
extern Vtx gWereCit3_Chest_mesh_layer_Opaque_vtx_0[49];
extern Gfx gWereCit3_Chest_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Head_mesh_layer_Opaque_vtx_0[114];
extern Gfx gWereCit3_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Head_mesh_layer_Opaque_vtx_1[16];
extern Gfx gWereCit3_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Head_mesh_layer_Opaque_vtx_2[5];
extern Gfx gWereCit3_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit3_Head_mesh_layer_Opaque_vtx_3[11];
extern Gfx gWereCit3_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gWereCit3_Head_mesh_layer_Opaque_vtx_4[36];
extern Gfx gWereCit3_Head_mesh_layer_Opaque_tri_4[];
extern Vtx gWereCit3_Shoulder_L_mesh_layer_Opaque_vtx_0[20];
extern Gfx gWereCit3_Shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Arm_L_mesh_layer_Opaque_vtx_0[15];
extern Gfx gWereCit3_Arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Arm_L_mesh_layer_Opaque_vtx_1[10];
extern Gfx gWereCit3_Arm_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Hand_L_mesh_layer_Opaque_vtx_0[51];
extern Gfx gWereCit3_Hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Hand_L_mesh_layer_Opaque_vtx_1[8];
extern Gfx gWereCit3_Hand_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Hand_L_mesh_layer_Opaque_vtx_2[20];
extern Gfx gWereCit3_Hand_L_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit3_Torch_mesh_layer_Opaque_vtx_0[20];
extern Gfx gWereCit3_Torch_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Torch_mesh_layer_Opaque_vtx_1[16];
extern Gfx gWereCit3_Torch_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Shoulder_R_mesh_layer_Opaque_vtx_0[24];
extern Gfx gWereCit3_Shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Arm_R_mesh_layer_Opaque_vtx_0[18];
extern Gfx gWereCit3_Arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Arm_R_mesh_layer_Opaque_vtx_1[10];
extern Gfx gWereCit3_Arm_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Hand_R_mesh_layer_Opaque_vtx_0[51];
extern Gfx gWereCit3_Hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Hand_R_mesh_layer_Opaque_vtx_1[8];
extern Gfx gWereCit3_Hand_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Hand_R_mesh_layer_Opaque_vtx_2[11];
extern Gfx gWereCit3_Hand_R_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit3_Weapon_mesh_layer_Opaque_vtx_0[15];
extern Gfx gWereCit3_Weapon_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Weapon_mesh_layer_Opaque_vtx_1[7];
extern Gfx gWereCit3_Weapon_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Tip_mesh_layer_Opaque_vtx_0[21];
extern Gfx gWereCit3_Tip_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Hip_mesh_layer_Opaque_vtx_0[21];
extern Gfx gWereCit3_Hip_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Hip_mesh_layer_Opaque_vtx_1[19];
extern Gfx gWereCit3_Hip_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Leg_L_mesh_layer_Opaque_vtx_0[24];
extern Gfx gWereCit3_Leg_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Shin_L_mesh_layer_Opaque_vtx_0[16];
extern Gfx gWereCit3_Shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Foot_L_mesh_layer_Opaque_vtx_0[40];
extern Gfx gWereCit3_Foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Foot_L_mesh_layer_Opaque_vtx_1[12];
extern Gfx gWereCit3_Foot_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit3_Leg_R_mesh_layer_Opaque_vtx_0[29];
extern Gfx gWereCit3_Leg_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Shin_R_mesh_layer_Opaque_vtx_0[16];
extern Gfx gWereCit3_Shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Foot_R_mesh_layer_Opaque_vtx_0[44];
extern Gfx gWereCit3_Foot_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit3_Foot_R_mesh_layer_Opaque_vtx_1[12];
extern Gfx gWereCit3_Foot_R_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gWereCit3_f3dlite_material_038_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_032_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_020_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_046_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_021_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_023_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_027_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_025_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_022_layerOpaque[];
extern Gfx mat_gWereCit3_f3dlite_material_013_layerOpaque[];
extern Gfx gWereCit3_Chest_mesh_layer_Opaque[];
extern Gfx gWereCit3_Head_mesh_layer_Opaque[];
extern Gfx gWereCit3_Shoulder_L_mesh_layer_Opaque[];
extern Gfx gWereCit3_Arm_L_mesh_layer_Opaque[];
extern Gfx gWereCit3_Hand_L_mesh_layer_Opaque[];
extern Gfx gWereCit3_Torch_mesh_layer_Opaque[];
extern Gfx gWereCit3_Shoulder_R_mesh_layer_Opaque[];
extern Gfx gWereCit3_Arm_R_mesh_layer_Opaque[];
extern Gfx gWereCit3_Hand_R_mesh_layer_Opaque[];
extern Gfx gWereCit3_Weapon_mesh_layer_Opaque[];
extern Gfx gWereCit3_Tip_mesh_layer_Opaque[];
extern Gfx gWereCit3_Hip_mesh_layer_Opaque[];
extern Gfx gWereCit3_Leg_L_mesh_layer_Opaque[];
extern Gfx gWereCit3_Shin_L_mesh_layer_Opaque[];
extern Gfx gWereCit3_Foot_L_mesh_layer_Opaque[];
extern Gfx gWereCit3_Leg_R_mesh_layer_Opaque[];
extern Gfx gWereCit3_Shin_R_mesh_layer_Opaque[];
extern Gfx gWereCit3_Foot_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gWereCit3;
#define GWERECIT3_ROOT_POS_LIMB 0
#define GWERECIT3_ROOT_ROT_LIMB 1
#define GWERECIT3_CHEST_LIMB 2
#define GWERECIT3_HEAD_LIMB 3
#define GWERECIT3_SHOULDER_L_LIMB 4
#define GWERECIT3_ARM_L_LIMB 5
#define GWERECIT3_HAND_L_LIMB 6
#define GWERECIT3_TORCH_LIMB 7
#define GWERECIT3_SHOULDER_R_LIMB 8
#define GWERECIT3_ARM_R_LIMB 9
#define GWERECIT3_HAND_R_LIMB 10
#define GWERECIT3_WEAPON_LIMB 11
#define GWERECIT3_TIP_LIMB 12
#define GWERECIT3_HIP_LIMB 13
#define GWERECIT3_LEG_L_LIMB 14
#define GWERECIT3_SHIN_L_LIMB 15
#define GWERECIT3_FOOT_L_LIMB 16
#define GWERECIT3_LEG_R_LIMB 17
#define GWERECIT3_SHIN_R_LIMB 18
#define GWERECIT3_FOOT_R_LIMB 19
#define GWERECIT3_NUM_LIMBS 20
