extern u64 gEldrSkel_CASTLEVANIA2_C5CE5837_2_0_E88337B5_ciByRGBA_ci4[];
extern u64 gEldrSkel_CASTLEVANIA2_C5CE5837_2_0_E88337B5_ciByRGBA_pal_rgba16[];
extern u64 gEldrSkel_CASTLEVANIA2_8D98C892_2_0_F8B0FBD2_ciByRGBA_ci4[];
extern u64 gEldrSkel_CASTLEVANIA2_8D98C892_2_0_F8B0FBD2_ciByRGBA_pal_rgba16[];
extern u64 gEldrSkel_CASTLEVANIA2_92534046_2_0_20B3F60E_ciByRGBA_ci4[];
extern u64 gEldrSkel_CASTLEVANIA2_92534046_2_0_20B3F60E_ciByRGBA_pal_rgba16[];
extern u64 gEldrSkel_CASTLEVANIA2_22DAB178_2_0_3005FCB3_ciByRGBA_ci4[];
extern u64 gEldrSkel_CASTLEVANIA2_22DAB178_2_0_3005FCB3_ciByRGBA_pal_rgba16[];
extern u64 gEldrSkel_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_ci4[];
extern u64 gEldrSkel_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_pal_rgba16[];
extern u64 gEldrSkel_CASTLEVANIA2_4DACF61D_2_0_1BC8E644_ciByRGBA_ci4[];
extern u64 gEldrSkel_CASTLEVANIA2_4DACF61D_2_0_1BC8E644_ciByRGBA_pal_rgba16[];
extern u64 gEldrSkel_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_ci4_copy[];
extern u64 gEldrSkel_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_pal_rgba16_copy[];
extern u64 gEldrSkel_shield_ia8[];
extern u64 gEldrSkel_organ_ci4[];
extern u64 gEldrSkel_organ_pal_rgba16[];
extern u64 gEldrSkel_CASTLEVANIA2_05D266F3_2_0_A6D0C9DB_ciByRGBA_ci4[];
extern u64 gEldrSkel_CASTLEVANIA2_05D266F3_2_0_A6D0C9DB_ciByRGBA_pal_rgba16[];
extern u64 gEldrSkel_boot_top_ci8_png_001_ci8[];
extern u64 gEldrSkel_boot_top_ci8_png_001_pal_rgba16[];
extern Vtx gEldrSkel_Root_mesh_layer_Opaque_vtx_0[17];
extern Gfx gEldrSkel_Root_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_Root_mesh_layer_Opaque_vtx_1[4];
extern Gfx gEldrSkel_Root_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_Root_mesh_layer_Opaque_vtx_2[7];
extern Gfx gEldrSkel_Root_mesh_layer_Opaque_tri_2[];
extern Vtx gEldrSkel_Abdomon_mesh_layer_Opaque_vtx_0[32];
extern Gfx gEldrSkel_Abdomon_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_Abdomon_mesh_layer_Opaque_vtx_1[43];
extern Gfx gEldrSkel_Abdomon_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_NeckLower_mesh_layer_Opaque_vtx_0[20];
extern Gfx gEldrSkel_NeckLower_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_NeckLower_mesh_layer_Opaque_vtx_1[4];
extern Gfx gEldrSkel_NeckLower_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_NeckUpper_mesh_layer_Opaque_vtx_0[26];
extern Gfx gEldrSkel_NeckUpper_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_NeckUpper_mesh_layer_Opaque_vtx_1[8];
extern Gfx gEldrSkel_NeckUpper_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_Head_mesh_layer_Opaque_vtx_0[51];
extern Gfx gEldrSkel_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_Head_mesh_layer_Opaque_vtx_1[72];
extern Gfx gEldrSkel_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_Head_mesh_layer_Opaque_vtx_2[168];
extern Gfx gEldrSkel_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gEldrSkel_Head_mesh_layer_Opaque_vtx_3[20];
extern Gfx gEldrSkel_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gEldrSkel_Head_mesh_layer_Opaque_vtx_4[10];
extern Gfx gEldrSkel_Head_mesh_layer_Opaque_tri_4[];
extern Vtx gEldrSkel_Tentacles_mesh_layer_Opaque_vtx_0[72];
extern Gfx gEldrSkel_Tentacles_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_ShoulderL_mesh_layer_Opaque_vtx_0[18];
extern Gfx gEldrSkel_ShoulderL_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_ShoulderL_mesh_layer_Opaque_vtx_1[4];
extern Gfx gEldrSkel_ShoulderL_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_ShoulderL_mesh_layer_Opaque_vtx_2[10];
extern Gfx gEldrSkel_ShoulderL_mesh_layer_Opaque_tri_2[];
extern Vtx gEldrSkel_ArmL_mesh_layer_Opaque_vtx_0[15];
extern Gfx gEldrSkel_ArmL_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_ArmL_mesh_layer_Opaque_vtx_1[4];
extern Gfx gEldrSkel_ArmL_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_HandL_mesh_layer_Opaque_vtx_0[10];
extern Gfx gEldrSkel_HandL_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_HandL_mesh_layer_Opaque_vtx_1[43];
extern Gfx gEldrSkel_HandL_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_HandLCont_mesh_layer_Opaque_vtx_0[6];
extern Gfx gEldrSkel_HandLCont_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_ShoulderR_mesh_layer_Opaque_vtx_0[4];
extern Gfx gEldrSkel_ShoulderR_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_ShoulderR_mesh_layer_Opaque_vtx_1[26];
extern Gfx gEldrSkel_ShoulderR_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_ShoulderR_mesh_layer_Opaque_vtx_2[4];
extern Gfx gEldrSkel_ShoulderR_mesh_layer_Opaque_tri_2[];
extern Vtx gEldrSkel_ArmR_mesh_layer_Opaque_vtx_0[18];
extern Gfx gEldrSkel_ArmR_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_ArmR_mesh_layer_Opaque_vtx_1[4];
extern Gfx gEldrSkel_ArmR_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_HandR_mesh_layer_Opaque_vtx_0[10];
extern Gfx gEldrSkel_HandR_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_HandR_mesh_layer_Opaque_vtx_1[43];
extern Gfx gEldrSkel_HandR_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_HandRCont_mesh_layer_Opaque_vtx_0[6];
extern Gfx gEldrSkel_HandRCont_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_LegL_mesh_layer_Opaque_vtx_0[11];
extern Gfx gEldrSkel_LegL_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_LegL_mesh_layer_Opaque_vtx_1[20];
extern Gfx gEldrSkel_LegL_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_ShinL_mesh_layer_Opaque_vtx_0[28];
extern Gfx gEldrSkel_ShinL_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_FootL_mesh_layer_Opaque_vtx_0[62];
extern Gfx gEldrSkel_FootL_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_FootL_mesh_layer_Opaque_vtx_1[30];
extern Gfx gEldrSkel_FootL_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_LegR_mesh_layer_Opaque_vtx_0[29];
extern Gfx gEldrSkel_LegR_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_LegR_mesh_layer_Opaque_vtx_1[8];
extern Gfx gEldrSkel_LegR_mesh_layer_Opaque_tri_1[];
extern Vtx gEldrSkel_LegR_mesh_layer_Opaque_vtx_2[3];
extern Gfx gEldrSkel_LegR_mesh_layer_Opaque_tri_2[];
extern Vtx gEldrSkel_ShinR_mesh_layer_Opaque_vtx_0[28];
extern Gfx gEldrSkel_ShinR_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_FootR_mesh_layer_Opaque_vtx_0[60];
extern Gfx gEldrSkel_FootR_mesh_layer_Opaque_tri_0[];
extern Vtx gEldrSkel_FootR_mesh_layer_Opaque_vtx_1[30];
extern Gfx gEldrSkel_FootR_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gEldrSkel_f3dlite_material_011_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_010_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_038_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_008_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_020_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_003_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_004_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_002_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_005_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_007_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_009_layerOpaque[];
extern Gfx mat_gEldrSkel_f3dlite_material_012_layerOpaque[];
extern Gfx gEldrSkel_Root_mesh_layer_Opaque[];
extern Gfx gEldrSkel_Abdomon_mesh_layer_Opaque[];
extern Gfx gEldrSkel_NeckLower_mesh_layer_Opaque[];
extern Gfx gEldrSkel_NeckUpper_mesh_layer_Opaque[];
extern Gfx gEldrSkel_Head_mesh_layer_Opaque[];
extern Gfx gEldrSkel_Tentacles_mesh_layer_Opaque[];
extern Gfx gEldrSkel_ShoulderL_mesh_layer_Opaque[];
extern Gfx gEldrSkel_ArmL_mesh_layer_Opaque[];
extern Gfx gEldrSkel_HandL_mesh_layer_Opaque[];
extern Gfx gEldrSkel_HandLCont_mesh_layer_Opaque[];
extern Gfx gEldrSkel_ShoulderR_mesh_layer_Opaque[];
extern Gfx gEldrSkel_ArmR_mesh_layer_Opaque[];
extern Gfx gEldrSkel_HandR_mesh_layer_Opaque[];
extern Gfx gEldrSkel_HandRCont_mesh_layer_Opaque[];
extern Gfx gEldrSkel_LegL_mesh_layer_Opaque[];
extern Gfx gEldrSkel_ShinL_mesh_layer_Opaque[];
extern Gfx gEldrSkel_FootL_mesh_layer_Opaque[];
extern Gfx gEldrSkel_LegR_mesh_layer_Opaque[];
extern Gfx gEldrSkel_ShinR_mesh_layer_Opaque[];
extern Gfx gEldrSkel_FootR_mesh_layer_Opaque[];
extern FlexSkeletonHeader gEldrSkel;
#define GELDRSKEL_ROOT_POS_LIMB 0
#define GELDRSKEL_ROOT_ROT_LIMB 1
#define GELDRSKEL_ABDOMON_LIMB 2
#define GELDRSKEL_NECKLOWER_LIMB 3
#define GELDRSKEL_NECKUPPER_LIMB 4
#define GELDRSKEL_HEAD_LIMB 5
#define GELDRSKEL_TENTACLES_LIMB 6
#define GELDRSKEL_SHOULDERL_LIMB 7
#define GELDRSKEL_ARML_LIMB 8
#define GELDRSKEL_HANDL_LIMB 9
#define GELDRSKEL_HANDLCONT_LIMB 10
#define GELDRSKEL_SHOULDERR_LIMB 11
#define GELDRSKEL_ARMR_LIMB 12
#define GELDRSKEL_HANDR_LIMB 13
#define GELDRSKEL_HANDRCONT_LIMB 14
#define GELDRSKEL_LEGL_LIMB 15
#define GELDRSKEL_SHINL_LIMB 16
#define GELDRSKEL_FOOTL_LIMB 17
#define GELDRSKEL_LEGR_LIMB 18
#define GELDRSKEL_SHINR_LIMB 19
#define GELDRSKEL_FOOTR_LIMB 20
#define GELDRSKEL_NUM_LIMBS 21
