extern u64 gWereCit2_CASTLEVANIA2_545EC560_2_0_40F408E6_ciByRGBA_ci4[];
extern u64 gWereCit2_CASTLEVANIA2_545EC560_2_0_40F408E6_ciByRGBA_pal_rgba16[];
extern u64 gWereCit2_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_ci4[];
extern u64 gWereCit2_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_pal_rgba16[];
extern u64 gWereCit2_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_ci4[];
extern u64 gWereCit2_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_pal_rgba16[];
extern u64 gWereCit2_uppermouth_i4[];
extern u64 gWereCit2_organ_ci4[];
extern u64 gWereCit2_organ_pal_rgba16[];
extern u64 gWereCit2_CASTLEVANIA2_0B423B84_2_0_E485EF34_ciByRGBA_ci4[];
extern u64 gWereCit2_CASTLEVANIA2_0B423B84_2_0_E485EF34_ciByRGBA_pal_rgba16[];
extern u64 gWereCit2_furcutout_ia8[];
extern u64 gWereCit2_boot_top_ci8_png_001_ci8[];
extern u64 gWereCit2_boot_top_ci8_png_001_pal_rgba16[];
extern u64 gWereCit2_CASTLEVANIA2_BCB03191_2_0_C6741D4F_ciByRGBA_ci4[];
extern u64 gWereCit2_CASTLEVANIA2_BCB03191_2_0_C6741D4F_ciByRGBA_pal_rgba16[];
extern u64 gWereCit2_boot_side_ci8_png_001_ci8[];
extern u64 gWereCit2_boot_side_ci8_png_001_pal_rgba16[];
extern Vtx gWereCit2_Chest_mesh_layer_Opaque_vtx_0[71];
extern Gfx gWereCit2_Chest_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Head_mesh_layer_Opaque_vtx_0[99];
extern Gfx gWereCit2_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Head_mesh_layer_Opaque_vtx_1[16];
extern Gfx gWereCit2_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Head_mesh_layer_Opaque_vtx_2[5];
extern Gfx gWereCit2_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit2_Head_mesh_layer_Opaque_vtx_3[11];
extern Gfx gWereCit2_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gWereCit2_Head_mesh_layer_Opaque_vtx_4[69];
extern Gfx gWereCit2_Head_mesh_layer_Opaque_tri_4[];
extern Vtx gWereCit2_Shoulder_L_mesh_layer_Opaque_vtx_0[20];
extern Gfx gWereCit2_Shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Arm_L_mesh_layer_Opaque_vtx_0[15];
extern Gfx gWereCit2_Arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Arm_L_mesh_layer_Opaque_vtx_1[10];
extern Gfx gWereCit2_Arm_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Hand_L_mesh_layer_Opaque_vtx_0[51];
extern Gfx gWereCit2_Hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Hand_L_mesh_layer_Opaque_vtx_1[8];
extern Gfx gWereCit2_Hand_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Shoulder_R_mesh_layer_Opaque_vtx_0[24];
extern Gfx gWereCit2_Shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Arm_R_mesh_layer_Opaque_vtx_0[18];
extern Gfx gWereCit2_Arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Arm_R_mesh_layer_Opaque_vtx_1[10];
extern Gfx gWereCit2_Arm_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Hand_R_mesh_layer_Opaque_vtx_0[51];
extern Gfx gWereCit2_Hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Hand_R_mesh_layer_Opaque_vtx_1[8];
extern Gfx gWereCit2_Hand_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Hand_R_mesh_layer_Opaque_vtx_2[11];
extern Gfx gWereCit2_Hand_R_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit2_Weapon_mesh_layer_Opaque_vtx_0[15];
extern Gfx gWereCit2_Weapon_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Weapon_mesh_layer_Opaque_vtx_1[36];
extern Gfx gWereCit2_Weapon_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Tip_mesh_layer_Opaque_vtx_0[9];
extern Gfx gWereCit2_Tip_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Hip_mesh_layer_Opaque_vtx_0[21];
extern Gfx gWereCit2_Hip_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Hip_mesh_layer_Opaque_vtx_1[16];
extern Gfx gWereCit2_Hip_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Leg_L_mesh_layer_Opaque_vtx_0[24];
extern Gfx gWereCit2_Leg_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Shin_L_mesh_layer_Opaque_vtx_0[16];
extern Gfx gWereCit2_Shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Foot_L_mesh_layer_Opaque_vtx_0[32];
extern Gfx gWereCit2_Foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Foot_L_mesh_layer_Opaque_vtx_1[12];
extern Gfx gWereCit2_Foot_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Foot_L_mesh_layer_Opaque_vtx_2[8];
extern Gfx gWereCit2_Foot_L_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit2_Leg_R_mesh_layer_Opaque_vtx_0[30];
extern Gfx gWereCit2_Leg_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Shin_R_mesh_layer_Opaque_vtx_0[16];
extern Gfx gWereCit2_Shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Foot_R_mesh_layer_Opaque_vtx_0[8];
extern Gfx gWereCit2_Foot_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit2_Foot_R_mesh_layer_Opaque_vtx_1[35];
extern Gfx gWereCit2_Foot_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit2_Foot_R_mesh_layer_Opaque_vtx_2[12];
extern Gfx gWereCit2_Foot_R_mesh_layer_Opaque_tri_2[];
extern Gfx mat_gWereCit2_f3dlite_material_038_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_032_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_020_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_046_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_021_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_022_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_023_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_012_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_layerOpaque[];
extern Gfx mat_gWereCit2_f3dlite_material_013_layerOpaque[];
extern Gfx gWereCit2_Chest_mesh_layer_Opaque[];
extern Gfx gWereCit2_Head_mesh_layer_Opaque[];
extern Gfx gWereCit2_Shoulder_L_mesh_layer_Opaque[];
extern Gfx gWereCit2_Arm_L_mesh_layer_Opaque[];
extern Gfx gWereCit2_Hand_L_mesh_layer_Opaque[];
extern Gfx gWereCit2_Shoulder_R_mesh_layer_Opaque[];
extern Gfx gWereCit2_Arm_R_mesh_layer_Opaque[];
extern Gfx gWereCit2_Hand_R_mesh_layer_Opaque[];
extern Gfx gWereCit2_Weapon_mesh_layer_Opaque[];
extern Gfx gWereCit2_Tip_mesh_layer_Opaque[];
extern Gfx gWereCit2_Hip_mesh_layer_Opaque[];
extern Gfx gWereCit2_Leg_L_mesh_layer_Opaque[];
extern Gfx gWereCit2_Shin_L_mesh_layer_Opaque[];
extern Gfx gWereCit2_Foot_L_mesh_layer_Opaque[];
extern Gfx gWereCit2_Leg_R_mesh_layer_Opaque[];
extern Gfx gWereCit2_Shin_R_mesh_layer_Opaque[];
extern Gfx gWereCit2_Foot_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gWereCit2;
#define GWERECIT2_ROOT_POS_LIMB 0
#define GWERECIT2_ROOT_ROT_LIMB 1
#define GWERECIT2_CHEST_LIMB 2
#define GWERECIT2_HEAD_LIMB 3
#define GWERECIT2_SHOULDER_L_LIMB 4
#define GWERECIT2_ARM_L_LIMB 5
#define GWERECIT2_HAND_L_LIMB 6
#define GWERECIT2_SHOULDER_R_LIMB 7
#define GWERECIT2_ARM_R_LIMB 8
#define GWERECIT2_HAND_R_LIMB 9
#define GWERECIT2_WEAPON_LIMB 10
#define GWERECIT2_TIP_LIMB 11
#define GWERECIT2_HIP_LIMB 12
#define GWERECIT2_LEG_L_LIMB 13
#define GWERECIT2_SHIN_L_LIMB 14
#define GWERECIT2_FOOT_L_LIMB 15
#define GWERECIT2_LEG_R_LIMB 16
#define GWERECIT2_SHIN_R_LIMB 17
#define GWERECIT2_FOOT_R_LIMB 18
#define GWERECIT2_NUM_LIMBS 19
