extern u64 gIronGateDL_CASTLEVANIA2_0F16526A_2_0_78ED1A7D_ciByRGBA_ci4[];
extern u64 gIronGateDL_CASTLEVANIA2_0F16526A_2_0_78ED1A7D_ciByRGBA_pal_rgba16[];
extern Vtx gIronGateDL_gIronGateDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gIronGateDL_gIronGateDL_mesh_layer_Opaque_vtx_0[8];
extern Gfx gIronGateDL_gIronGateDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gIronGateDL_IronGate_layerOpaque[];
extern Gfx gIronGateDL[];
