extern u64 gSkelskel_CASTLEVANIA2_8E3C0934_2_0_CBA10CBC_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_8E3C0934_2_0_CBA10CBC_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_CASTLEVANIA2_102C1159_2_0_1AE64037_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_102C1159_2_0_1AE64037_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_CASTLEVANIA2_8D72674B_2_0_5E464B49_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_8D72674B_2_0_5E464B49_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_CASTLEVANIA2_7D5C5A80_2_0_DC871AC9_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_7D5C5A80_2_0_DC871AC9_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_CASTLEVANIA2_3280C270_2_0_2A51B8BA_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_3280C270_2_0_2A51B8BA_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_CASTLEVANIA2_7F4EC577_2_0_B6A48AF2_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_7F4EC577_2_0_B6A48AF2_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_chaini4_i4[];
extern u64 gSkelskel_CASTLEVANIA2_AD08AD99_2_0_468E000A_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_AD08AD99_2_0_468E000A_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_shield_ia8[];
extern u64 gSkelskel_CASTLEVANIA2_0A7BD12F_2_0_30BB40D2_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_0A7BD12F_2_0_30BB40D2_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_CASTLEVANIA2_EEAB02A5_2_0_5D4AEAF5_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_EEAB02A5_2_0_5D4AEAF5_ciByRGBA_pal_rgba16[];
extern u64 gSkelskel_CASTLEVANIA2_2ED1327E_2_0_6062865C_ciByRGBA_ci4[];
extern u64 gSkelskel_CASTLEVANIA2_2ED1327E_2_0_6062865C_ciByRGBA_pal_rgba16[];
extern Vtx gSkelskel_Hip_mesh_layer_Opaque_vtx_0[24];
extern Gfx gSkelskel_Hip_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Leg_l_mesh_layer_Opaque_vtx_0[13];
extern Gfx gSkelskel_Leg_l_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Shin_l_mesh_layer_Opaque_vtx_0[23];
extern Gfx gSkelskel_Shin_l_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Foot_l_mesh_layer_Opaque_vtx_0[6];
extern Gfx gSkelskel_Foot_l_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Leg_r_mesh_layer_Opaque_vtx_0[13];
extern Gfx gSkelskel_Leg_r_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Shin_r_mesh_layer_Opaque_vtx_0[23];
extern Gfx gSkelskel_Shin_r_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Foot_r_mesh_layer_Opaque_vtx_0[6];
extern Gfx gSkelskel_Foot_r_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Lumbar_mesh_layer_Opaque_vtx_0[8];
extern Gfx gSkelskel_Lumbar_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Thorax_mesh_layer_Opaque_vtx_0[67];
extern Gfx gSkelskel_Thorax_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Thorax_mesh_layer_Opaque_vtx_1[16];
extern Gfx gSkelskel_Thorax_mesh_layer_Opaque_tri_1[];
extern Vtx gSkelskel_Cervical_mesh_layer_Opaque_vtx_0[11];
extern Gfx gSkelskel_Cervical_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Head_mesh_layer_Opaque_vtx_0[20];
extern Gfx gSkelskel_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Head_mesh_layer_Opaque_vtx_1[16];
extern Gfx gSkelskel_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gSkelskel_Head_mesh_layer_Opaque_vtx_2[24];
extern Gfx gSkelskel_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gSkelskel_Head_mesh_layer_Opaque_vtx_3[10];
extern Gfx gSkelskel_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gSkelskel_Mouth_mesh_layer_Opaque_vtx_0[11];
extern Gfx gSkelskel_Mouth_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Shoulder_l_mesh_layer_Opaque_vtx_0[11];
extern Gfx gSkelskel_Shoulder_l_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Arm_l_mesh_layer_Opaque_vtx_0[8];
extern Gfx gSkelskel_Arm_l_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Hand_l_mesh_layer_Opaque_vtx_0[6];
extern Gfx gSkelskel_Hand_l_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Hand_l_mesh_layer_Opaque_vtx_1[17];
extern Gfx gSkelskel_Hand_l_mesh_layer_Opaque_tri_1[];
extern Vtx gSkelskel_Hand_l_mesh_layer_Opaque_vtx_2[32];
extern Gfx gSkelskel_Hand_l_mesh_layer_Opaque_tri_2[];
extern Vtx gSkelskel_Hand_l_mesh_layer_Opaque_vtx_3[96];
extern Gfx gSkelskel_Hand_l_mesh_layer_Opaque_tri_3[];
extern Vtx gSkelskel_Shoulder_r_mesh_layer_Opaque_vtx_0[11];
extern Gfx gSkelskel_Shoulder_r_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Arm_r_mesh_layer_Opaque_vtx_0[8];
extern Gfx gSkelskel_Arm_r_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Hand_r_mesh_layer_Opaque_vtx_0[6];
extern Gfx gSkelskel_Hand_r_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Weapon_mesh_layer_Opaque_vtx_0[4];
extern Gfx gSkelskel_Weapon_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Blade_mesh_layer_Opaque_vtx_0[15];
extern Gfx gSkelskel_Blade_mesh_layer_Opaque_tri_0[];
extern Vtx gSkelskel_Blade_mesh_layer_Opaque_vtx_1[20];
extern Gfx gSkelskel_Blade_mesh_layer_Opaque_tri_1[];
extern Vtx gSkelskel_Tip_mesh_layer_Opaque_vtx_0[17];
extern Gfx gSkelskel_Tip_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gSkelskel_Legs_layerOpaque[];
extern Gfx mat_gSkelskel_Body_layerOpaque[];
extern Gfx mat_gSkelskel_Tattered_Rags_layerOpaque[];
extern Gfx mat_gSkelskel_Head_layerOpaque[];
extern Gfx mat_gSkelskel_Helm_layerOpaque[];
extern Gfx mat_gSkelskel_Rim_layerOpaque[];
extern Gfx mat_gSkelskel_Mail_layerOpaque[];
extern Gfx mat_gSkelskel_Arms_layerOpaque[];
extern Gfx mat_gSkelskel_Boss_layerOpaque[];
extern Gfx mat_gSkelskel_Wood_layerOpaque[];
extern Gfx mat_gSkelskel_Hilt_layerOpaque[];
extern Gfx mat_gSkelskel_Blade_layerOpaque[];
extern Gfx gSkelskel_Hip_mesh_layer_Opaque[];
extern Gfx gSkelskel_Leg_l_mesh_layer_Opaque[];
extern Gfx gSkelskel_Shin_l_mesh_layer_Opaque[];
extern Gfx gSkelskel_Foot_l_mesh_layer_Opaque[];
extern Gfx gSkelskel_Leg_r_mesh_layer_Opaque[];
extern Gfx gSkelskel_Shin_r_mesh_layer_Opaque[];
extern Gfx gSkelskel_Foot_r_mesh_layer_Opaque[];
extern Gfx gSkelskel_Lumbar_mesh_layer_Opaque[];
extern Gfx gSkelskel_Thorax_mesh_layer_Opaque[];
extern Gfx gSkelskel_Cervical_mesh_layer_Opaque[];
extern Gfx gSkelskel_Head_mesh_layer_Opaque[];
extern Gfx gSkelskel_Mouth_mesh_layer_Opaque[];
extern Gfx gSkelskel_Shoulder_l_mesh_layer_Opaque[];
extern Gfx gSkelskel_Arm_l_mesh_layer_Opaque[];
extern Gfx gSkelskel_Hand_l_mesh_layer_Opaque[];
extern Gfx gSkelskel_Shoulder_r_mesh_layer_Opaque[];
extern Gfx gSkelskel_Arm_r_mesh_layer_Opaque[];
extern Gfx gSkelskel_Hand_r_mesh_layer_Opaque[];
extern Gfx gSkelskel_Weapon_mesh_layer_Opaque[];
extern Gfx gSkelskel_Blade_mesh_layer_Opaque[];
extern Gfx gSkelskel_Tip_mesh_layer_Opaque[];
extern FlexSkeletonHeader gSkelskel;
#define GSKELSKEL_HIP_POS_LIMB 0
#define GSKELSKEL_HIP_ROT_LIMB 1
#define GSKELSKEL_LEG_L_LIMB 2
#define GSKELSKEL_SHIN_L_LIMB 3
#define GSKELSKEL_FOOT_L_LIMB 4
#define GSKELSKEL_LEG_R_LIMB 5
#define GSKELSKEL_SHIN_R_LIMB 6
#define GSKELSKEL_FOOT_R_LIMB 7
#define GSKELSKEL_LUMBAR_LIMB 8
#define GSKELSKEL_THORAX_LIMB 9
#define GSKELSKEL_CERVICAL_LIMB 10
#define GSKELSKEL_HEAD_LIMB 11
#define GSKELSKEL_MOUTH_LIMB 12
#define GSKELSKEL_SHOULDER_L_LIMB 13
#define GSKELSKEL_ARM_L_LIMB 14
#define GSKELSKEL_HAND_L_LIMB 15
#define GSKELSKEL_SHOULDER_R_LIMB 16
#define GSKELSKEL_ARM_R_LIMB 17
#define GSKELSKEL_HAND_R_LIMB 18
#define GSKELSKEL_WEAPON_LIMB 19
#define GSKELSKEL_BLADE_LIMB 20
#define GSKELSKEL_TIP_LIMB 21
#define GSKELSKEL_NUM_LIMBS 22
