extern u64 gthefather_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_ci4[];
extern u64 gthefather_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_pal_rgba16[];
extern u64 gthefather_furcutout_ia8[];
extern u64 gthefather_hoof_i4[];
extern u64 gthefather_organ_ci4[];
extern u64 gthefather_organ_pal_rgba16[];
extern u64 gthefather_ribs_ci8[];
extern u64 gthefather_ribs_pal_rgba16[];
extern u64 gthefather_dogmouth_i4[];
extern u64 gthefather_uppermouth_i4[];
extern u64 gthefather_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_ci4[];
extern u64 gthefather_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_pal_rgba16[];
extern Vtx gthefather_Hip_mesh_layer_Opaque_vtx_0[10];
extern Gfx gthefather_Hip_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Hip_mesh_layer_Opaque_vtx_1[24];
extern Gfx gthefather_Hip_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_UpperLeg_L_mesh_layer_Opaque_vtx_0[31];
extern Gfx gthefather_UpperLeg_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_UpperLeg_L_mesh_layer_Opaque_vtx_1[44];
extern Gfx gthefather_UpperLeg_L_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Shin_L_mesh_layer_Opaque_vtx_0[68];
extern Gfx gthefather_Shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Shin_L_mesh_layer_Opaque_vtx_1[14];
extern Gfx gthefather_Shin_L_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Hoof_L_mesh_layer_Opaque_vtx_0[14];
extern Gfx gthefather_Hoof_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Hoof_L_mesh_layer_Opaque_vtx_1[21];
extern Gfx gthefather_Hoof_L_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Hoof_L_mesh_layer_Opaque_vtx_2[16];
extern Gfx gthefather_Hoof_L_mesh_layer_Opaque_tri_2[];
extern Vtx gthefather_UpperLeg_R_mesh_layer_Opaque_vtx_0[31];
extern Gfx gthefather_UpperLeg_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_UpperLeg_R_mesh_layer_Opaque_vtx_1[44];
extern Gfx gthefather_UpperLeg_R_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Shin_R_mesh_layer_Opaque_vtx_0[56];
extern Gfx gthefather_Shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Shin_R_mesh_layer_Opaque_vtx_1[14];
extern Gfx gthefather_Shin_R_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Hoof_R_mesh_layer_Opaque_vtx_0[18];
extern Gfx gthefather_Hoof_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Hoof_R_mesh_layer_Opaque_vtx_1[21];
extern Gfx gthefather_Hoof_R_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Hoof_R_mesh_layer_Opaque_vtx_2[16];
extern Gfx gthefather_Hoof_R_mesh_layer_Opaque_tri_2[];
extern Vtx gthefather_Torso_mesh_layer_Opaque_vtx_0[24];
extern Gfx gthefather_Torso_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Torso_mesh_layer_Opaque_vtx_1[10];
extern Gfx gthefather_Torso_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Chest_mesh_layer_Opaque_vtx_0[51];
extern Gfx gthefather_Chest_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Chest_mesh_layer_Opaque_vtx_1[17];
extern Gfx gthefather_Chest_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Chest_mesh_layer_Opaque_vtx_2[6];
extern Gfx gthefather_Chest_mesh_layer_Opaque_tri_2[];
extern Vtx gthefather_Chest_mesh_layer_Opaque_vtx_3[50];
extern Gfx gthefather_Chest_mesh_layer_Opaque_tri_3[];
extern Vtx gthefather_Chest_mesh_layer_Opaque_vtx_4[10];
extern Gfx gthefather_Chest_mesh_layer_Opaque_tri_4[];
extern Vtx gthefather_Neck_mesh_layer_Opaque_vtx_0[18];
extern Gfx gthefather_Neck_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Head_mesh_layer_Opaque_vtx_0[103];
extern Gfx gthefather_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Head_mesh_layer_Opaque_vtx_1[5];
extern Gfx gthefather_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Head_mesh_layer_Opaque_vtx_2[19];
extern Gfx gthefather_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gthefather_Head_mesh_layer_Opaque_vtx_3[238];
extern Gfx gthefather_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gthefather_Jaw_mesh_layer_Opaque_vtx_0[47];
extern Gfx gthefather_Jaw_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Jaw_mesh_layer_Opaque_vtx_1[9];
extern Gfx gthefather_Jaw_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Jaw_mesh_layer_Opaque_vtx_2[14];
extern Gfx gthefather_Jaw_mesh_layer_Opaque_tri_2[];
extern Vtx gthefather_Shoulder_L_mesh_layer_Opaque_vtx_0[22];
extern Gfx gthefather_Shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Shoulder_L_mesh_layer_Opaque_vtx_1[12];
extern Gfx gthefather_Shoulder_L_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Arm_L_mesh_layer_Opaque_vtx_0[52];
extern Gfx gthefather_Arm_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Arm_L_mesh_layer_Opaque_vtx_1[10];
extern Gfx gthefather_Arm_L_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Hand_L_mesh_layer_Opaque_vtx_0[24];
extern Gfx gthefather_Hand_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_IndexF_L_mesh_layer_Opaque_vtx_0[14];
extern Gfx gthefather_IndexF_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Index2L_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Index2L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_MiddleF_L_mesh_layer_Opaque_vtx_0[14];
extern Gfx gthefather_MiddleF_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Middle2L_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Middle2L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_PinkyF_L_mesh_layer_Opaque_vtx_0[10];
extern Gfx gthefather_PinkyF_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Pinky2L_mesh_layer_Opaque_vtx_0[8];
extern Gfx gthefather_Pinky2L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_RingF_L_mesh_layer_Opaque_vtx_0[14];
extern Gfx gthefather_RingF_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Ring2L_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Ring2L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_ThumbF_L_mesh_layer_Opaque_vtx_0[12];
extern Gfx gthefather_ThumbF_L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Thumb2L_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Thumb2L_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Shoulder_R_mesh_layer_Opaque_vtx_0[22];
extern Gfx gthefather_Shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Shoulder_R_mesh_layer_Opaque_vtx_1[12];
extern Gfx gthefather_Shoulder_R_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Arm_R_mesh_layer_Opaque_vtx_0[53];
extern Gfx gthefather_Arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Arm_R_mesh_layer_Opaque_vtx_1[10];
extern Gfx gthefather_Arm_R_mesh_layer_Opaque_tri_1[];
extern Vtx gthefather_Hand_R_mesh_layer_Opaque_vtx_0[24];
extern Gfx gthefather_Hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_IndexF_R_mesh_layer_Opaque_vtx_0[14];
extern Gfx gthefather_IndexF_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Index2R_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Index2R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_MiddleF_R_mesh_layer_Opaque_vtx_0[14];
extern Gfx gthefather_MiddleF_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Middle2R_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Middle2R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_PinkyF_R_mesh_layer_Opaque_vtx_0[10];
extern Gfx gthefather_PinkyF_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Pinky2R_mesh_layer_Opaque_vtx_0[8];
extern Gfx gthefather_Pinky2R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_RingF_R_mesh_layer_Opaque_vtx_0[14];
extern Gfx gthefather_RingF_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Ring2R_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Ring2R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_ThumbF_R_mesh_layer_Opaque_vtx_0[12];
extern Gfx gthefather_ThumbF_R_mesh_layer_Opaque_tri_0[];
extern Vtx gthefather_Thumb2R_mesh_layer_Opaque_vtx_0[9];
extern Gfx gthefather_Thumb2R_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gthefather_f3dlite_material_004_layerOpaque[];
extern Gfx mat_gthefather_f3dlite_material_008_layerOpaque[];
extern Gfx mat_gthefather_f3dlite_material_019_layerOpaque[];
extern Gfx mat_gthefather_f3dlite_material_003_layerOpaque[];
extern Gfx mat_gthefather_f3dlite_material_002_layerOpaque[];
extern Gfx mat_gthefather_f3dlite_material_006_layerOpaque[];
extern Gfx mat_gthefather_f3dlite_material_007_layerOpaque[];
extern Gfx mat_gthefather_f3dlite_material_005_layerOpaque[];
extern Gfx gthefather_Hip_mesh_layer_Opaque[];
extern Gfx gthefather_UpperLeg_L_mesh_layer_Opaque[];
extern Gfx gthefather_Shin_L_mesh_layer_Opaque[];
extern Gfx gthefather_Hoof_L_mesh_layer_Opaque[];
extern Gfx gthefather_UpperLeg_R_mesh_layer_Opaque[];
extern Gfx gthefather_Shin_R_mesh_layer_Opaque[];
extern Gfx gthefather_Hoof_R_mesh_layer_Opaque[];
extern Gfx gthefather_Torso_mesh_layer_Opaque[];
extern Gfx gthefather_Chest_mesh_layer_Opaque[];
extern Gfx gthefather_Neck_mesh_layer_Opaque[];
extern Gfx gthefather_Head_mesh_layer_Opaque[];
extern Gfx gthefather_Jaw_mesh_layer_Opaque[];
extern Gfx gthefather_Shoulder_L_mesh_layer_Opaque[];
extern Gfx gthefather_Arm_L_mesh_layer_Opaque[];
extern Gfx gthefather_Hand_L_mesh_layer_Opaque[];
extern Gfx gthefather_IndexF_L_mesh_layer_Opaque[];
extern Gfx gthefather_Index2L_mesh_layer_Opaque[];
extern Gfx gthefather_MiddleF_L_mesh_layer_Opaque[];
extern Gfx gthefather_Middle2L_mesh_layer_Opaque[];
extern Gfx gthefather_PinkyF_L_mesh_layer_Opaque[];
extern Gfx gthefather_Pinky2L_mesh_layer_Opaque[];
extern Gfx gthefather_RingF_L_mesh_layer_Opaque[];
extern Gfx gthefather_Ring2L_mesh_layer_Opaque[];
extern Gfx gthefather_ThumbF_L_mesh_layer_Opaque[];
extern Gfx gthefather_Thumb2L_mesh_layer_Opaque[];
extern Gfx gthefather_Shoulder_R_mesh_layer_Opaque[];
extern Gfx gthefather_Arm_R_mesh_layer_Opaque[];
extern Gfx gthefather_Hand_R_mesh_layer_Opaque[];
extern Gfx gthefather_IndexF_R_mesh_layer_Opaque[];
extern Gfx gthefather_Index2R_mesh_layer_Opaque[];
extern Gfx gthefather_MiddleF_R_mesh_layer_Opaque[];
extern Gfx gthefather_Middle2R_mesh_layer_Opaque[];
extern Gfx gthefather_PinkyF_R_mesh_layer_Opaque[];
extern Gfx gthefather_Pinky2R_mesh_layer_Opaque[];
extern Gfx gthefather_RingF_R_mesh_layer_Opaque[];
extern Gfx gthefather_Ring2R_mesh_layer_Opaque[];
extern Gfx gthefather_ThumbF_R_mesh_layer_Opaque[];
extern Gfx gthefather_Thumb2R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gthefather;
#define GTHEFATHER_ROOT_POS_LIMB 0
#define GTHEFATHER_ROOT_ROT_LIMB 1
#define GTHEFATHER_HIP_LIMB 2
#define GTHEFATHER_UPPERLEG_L_LIMB 3
#define GTHEFATHER_SHIN_L_LIMB 4
#define GTHEFATHER_HOOF_L_LIMB 5
#define GTHEFATHER_UPPERLEG_R_LIMB 6
#define GTHEFATHER_SHIN_R_LIMB 7
#define GTHEFATHER_HOOF_R_LIMB 8
#define GTHEFATHER_TORSO_LIMB 9
#define GTHEFATHER_CHEST_LIMB 10
#define GTHEFATHER_NECK_LIMB 11
#define GTHEFATHER_HEAD_LIMB 12
#define GTHEFATHER_JAW_LIMB 13
#define GTHEFATHER_SHOULDER_L_LIMB 14
#define GTHEFATHER_ARM_L_LIMB 15
#define GTHEFATHER_HAND_L_LIMB 16
#define GTHEFATHER_INDEXF_L_LIMB 17
#define GTHEFATHER_INDEX2L_LIMB 18
#define GTHEFATHER_MIDDLEF_L_LIMB 19
#define GTHEFATHER_MIDDLE2L_LIMB 20
#define GTHEFATHER_PINKYF_L_LIMB 21
#define GTHEFATHER_PINKY2L_LIMB 22
#define GTHEFATHER_RINGF_L_LIMB 23
#define GTHEFATHER_RING2L_LIMB 24
#define GTHEFATHER_THUMBF_L_LIMB 25
#define GTHEFATHER_THUMB2L_LIMB 26
#define GTHEFATHER_SHOULDER_R_LIMB 27
#define GTHEFATHER_ARM_R_LIMB 28
#define GTHEFATHER_HAND_R_LIMB 29
#define GTHEFATHER_INDEXF_R_LIMB 30
#define GTHEFATHER_INDEX2R_LIMB 31
#define GTHEFATHER_MIDDLEF_R_LIMB 32
#define GTHEFATHER_MIDDLE2R_LIMB 33
#define GTHEFATHER_PINKYF_R_LIMB 34
#define GTHEFATHER_PINKY2R_LIMB 35
#define GTHEFATHER_RINGF_R_LIMB 36
#define GTHEFATHER_RING2R_LIMB 37
#define GTHEFATHER_THUMBF_R_LIMB 38
#define GTHEFATHER_THUMB2R_LIMB 39
#define GTHEFATHER_NUM_LIMBS 40
