extern u64 Armature_thorax_ci4[];
extern u64 Armature_thorax_pal_rgba16[];
extern u64 Armature_shield_ia8[];
extern u64 Armature_abdomon_ci4[];
extern u64 Armature_abdomon_pal_rgba16[];
extern u64 Armature_legseg_rgba16[];
extern u64 Armature_mandibl_rgba16[];
extern Vtx Armature_waist_mesh_layer_Opaque_vtx_0[36];
extern Gfx Armature_waist_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_waist_mesh_layer_Opaque_vtx_1[32];
extern Gfx Armature_waist_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_abdomen_mesh_layer_Opaque_vtx_0[23];
extern Gfx Armature_abdomen_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legl1_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_legl1_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legl1_mesh_layer_Opaque_vtx_1[8];
extern Gfx Armature_legl1_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegl1_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_forelegl1_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegl1_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_forelegl1_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_legl2_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_legl2_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legl2_mesh_layer_Opaque_vtx_1[8];
extern Gfx Armature_legl2_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegl2_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_forelegl2_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegl2_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_forelegl2_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_legl3_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_legl3_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legl3_mesh_layer_Opaque_vtx_1[8];
extern Gfx Armature_legl3_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegl3_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_forelegl3_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegl3_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_forelegl3_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_legl4_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_legl4_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legl4_mesh_layer_Opaque_vtx_1[8];
extern Gfx Armature_legl4_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegl4_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_forelegl4_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegl4_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_forelegl4_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_legr1_mesh_layer_Opaque_vtx_0[8];
extern Gfx Armature_legr1_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legr1_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_legr1_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegr1_mesh_layer_Opaque_vtx_0[9];
extern Gfx Armature_forelegr1_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegr1_mesh_layer_Opaque_vtx_1[4];
extern Gfx Armature_forelegr1_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_legr2_mesh_layer_Opaque_vtx_0[8];
extern Gfx Armature_legr2_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legr2_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_legr2_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegr2_mesh_layer_Opaque_vtx_0[9];
extern Gfx Armature_forelegr2_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegr2_mesh_layer_Opaque_vtx_1[4];
extern Gfx Armature_forelegr2_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_legr3_mesh_layer_Opaque_vtx_0[8];
extern Gfx Armature_legr3_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legr3_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_legr3_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegr3_mesh_layer_Opaque_vtx_0[9];
extern Gfx Armature_forelegr3_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegr3_mesh_layer_Opaque_vtx_1[4];
extern Gfx Armature_forelegr3_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_legr4_mesh_layer_Opaque_vtx_0[8];
extern Gfx Armature_legr4_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_legr4_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_legr4_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_forelegr4_mesh_layer_Opaque_vtx_0[9];
extern Gfx Armature_forelegr4_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_forelegr4_mesh_layer_Opaque_vtx_1[4];
extern Gfx Armature_forelegr4_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_mandiblel_mesh_layer_Opaque_vtx_0[12];
extern Gfx Armature_mandiblel_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_mandiblel_mesh_layer_Opaque_vtx_1[9];
extern Gfx Armature_mandiblel_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_mandibler_mesh_layer_Opaque_vtx_0[18];
extern Gfx Armature_mandibler_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_mandibler_mesh_layer_Opaque_vtx_1[7];
extern Gfx Armature_mandibler_mesh_layer_Opaque_tri_1[];
extern Gfx mat_Armature_f3dlite_material_001_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_003_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_002_layerOpaque[];
extern Gfx mat_Armature_f3dlite_material_006_layerOpaque[];
extern Gfx Armature_waist_mesh_layer_Opaque[];
extern Gfx Armature_abdomen_mesh_layer_Opaque[];
extern Gfx Armature_legl1_mesh_layer_Opaque[];
extern Gfx Armature_forelegl1_mesh_layer_Opaque[];
extern Gfx Armature_legl2_mesh_layer_Opaque[];
extern Gfx Armature_forelegl2_mesh_layer_Opaque[];
extern Gfx Armature_legl3_mesh_layer_Opaque[];
extern Gfx Armature_forelegl3_mesh_layer_Opaque[];
extern Gfx Armature_legl4_mesh_layer_Opaque[];
extern Gfx Armature_forelegl4_mesh_layer_Opaque[];
extern Gfx Armature_legr1_mesh_layer_Opaque[];
extern Gfx Armature_forelegr1_mesh_layer_Opaque[];
extern Gfx Armature_legr2_mesh_layer_Opaque[];
extern Gfx Armature_forelegr2_mesh_layer_Opaque[];
extern Gfx Armature_legr3_mesh_layer_Opaque[];
extern Gfx Armature_forelegr3_mesh_layer_Opaque[];
extern Gfx Armature_legr4_mesh_layer_Opaque[];
extern Gfx Armature_forelegr4_mesh_layer_Opaque[];
extern Gfx Armature_mandiblel_mesh_layer_Opaque[];
extern Gfx Armature_mandibler_mesh_layer_Opaque[];
extern FlexSkeletonHeader Armature;
#define ARMATURE_ROOT_POS_LIMB 0
#define ARMATURE_ROOT_ROT_LIMB 1
#define ARMATURE_WAIST_LIMB 2
#define ARMATURE_ABDOMEN_LIMB 3
#define ARMATURE_LEGL1_LIMB 4
#define ARMATURE_FORELEGL1_LIMB 5
#define ARMATURE_LEGL2_LIMB 6
#define ARMATURE_FORELEGL2_LIMB 7
#define ARMATURE_LEGL3_LIMB 8
#define ARMATURE_FORELEGL3_LIMB 9
#define ARMATURE_LEGL4_LIMB 10
#define ARMATURE_FORELEGL4_LIMB 11
#define ARMATURE_LEGR1_LIMB 12
#define ARMATURE_FORELEGR1_LIMB 13
#define ARMATURE_LEGR2_LIMB 14
#define ARMATURE_FORELEGR2_LIMB 15
#define ARMATURE_LEGR3_LIMB 16
#define ARMATURE_FORELEGR3_LIMB 17
#define ARMATURE_LEGR4_LIMB 18
#define ARMATURE_FORELEGR4_LIMB 19
#define ARMATURE_MANDIBLEL_LIMB 20
#define ARMATURE_MANDIBLER_LIMB 21
#define ARMATURE_NUM_LIMBS 22
