extern u64 gWereCit_CASTLEVANIA2_363D160E_2_0_06AB74FC_ciByRGBA_ci4[];
extern u64 gWereCit_CASTLEVANIA2_363D160E_2_0_06AB74FC_ciByRGBA_pal_rgba16[];
extern u64 gWereCit_CASTLEVANIA2_D328BD18_2_0_48490F1A_ciByRGBA_ci4[];
extern u64 gWereCit_CASTLEVANIA2_D328BD18_2_0_48490F1A_ciByRGBA_pal_rgba16[];
extern u64 gWereCit_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_ci4[];
extern u64 gWereCit_CASTLEVANIA2_C69CF394_2_0_6F8BB677_ciByRGBA_pal_rgba16[];
extern u64 gWereCit_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_ci4[];
extern u64 gWereCit_CASTLEVANIA2_F5E4DD5E_2_0_BDD5A5BB_ciByRGBA_pal_rgba16[];
extern u64 gWereCit_cloth_ci8_png_001_ci8[];
extern u64 gWereCit_cloth_ci8_png_001_pal_rgba16[];
extern u64 gWereCit_furcutout_ia8[];
extern u64 gWereCit_bloodybandage_ci4[];
extern u64 gWereCit_bloodybandage_pal_rgba16[];
extern u64 gWereCit_CASTLEVANIA2_EEAB02A5_2_0_5D4AEAF5_ciByRGBA_ci4[];
extern u64 gWereCit_CASTLEVANIA2_EEAB02A5_2_0_5D4AEAF5_ciByRGBA_pal_rgba16[];
extern u64 gWereCit_CASTLEVANIA2_CD671B29_2_0_CB4C8B0E_ciByRGBA_ci4[];
extern u64 gWereCit_CASTLEVANIA2_CD671B29_2_0_CB4C8B0E_ciByRGBA_pal_rgba16[];
extern u64 gWereCit_cloth_stain_ci8_png_001_ci8[];
extern u64 gWereCit_cloth_stain_ci8_png_001_pal_rgba16[];
extern u64 gWereCit_boot_side_ci8_png_001_ci8[];
extern u64 gWereCit_boot_side_ci8_png_001_pal_rgba16[];
extern u64 gWereCit_boot_top_ci8_png_001_ci8[];
extern u64 gWereCit_boot_top_ci8_png_001_pal_rgba16[];
extern Vtx gWereCit_Chest_mesh_layer_Opaque_vtx_0[45];
extern Gfx gWereCit_Chest_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Chest_mesh_layer_Opaque_vtx_1[6];
extern Gfx gWereCit_Chest_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Head_mesh_layer_Opaque_vtx_0[109];
extern Gfx gWereCit_Head_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Head_mesh_layer_Opaque_vtx_1[16];
extern Gfx gWereCit_Head_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Head_mesh_layer_Opaque_vtx_2[7];
extern Gfx gWereCit_Head_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit_Head_mesh_layer_Opaque_vtx_3[58];
extern Gfx gWereCit_Head_mesh_layer_Opaque_tri_3[];
extern Vtx gWereCit_Shoulder_L_mesh_layer_Opaque_vtx_0[8];
extern Gfx gWereCit_Shoulder_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Shoulder_L_mesh_layer_Opaque_vtx_1[10];
extern Gfx gWereCit_Shoulder_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Shoulder_L_mesh_layer_Opaque_vtx_2[4];
extern Gfx gWereCit_Shoulder_L_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit_Shoulder_L_mesh_layer_Opaque_vtx_3[14];
extern Gfx gWereCit_Shoulder_L_mesh_layer_Opaque_tri_3[];
extern Vtx gWereCit_Shoulder_R_mesh_layer_Opaque_vtx_0[9];
extern Gfx gWereCit_Shoulder_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Shoulder_R_mesh_layer_Opaque_vtx_1[3];
extern Gfx gWereCit_Shoulder_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Shoulder_R_mesh_layer_Opaque_vtx_2[10];
extern Gfx gWereCit_Shoulder_R_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit_Shoulder_R_mesh_layer_Opaque_vtx_3[4];
extern Gfx gWereCit_Shoulder_R_mesh_layer_Opaque_tri_3[];
extern Vtx gWereCit_Arm_R_mesh_layer_Opaque_vtx_0[15];
extern Gfx gWereCit_Arm_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Arm_R_mesh_layer_Opaque_vtx_1[4];
extern Gfx gWereCit_Arm_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Hand_R_mesh_layer_Opaque_vtx_0[51];
extern Gfx gWereCit_Hand_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Hand_R_mesh_layer_Opaque_vtx_1[9];
extern Gfx gWereCit_Hand_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Hand_R_mesh_layer_Opaque_vtx_2[8];
extern Gfx gWereCit_Hand_R_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit_Weapon_mesh_layer_Opaque_vtx_0[14];
extern Gfx gWereCit_Weapon_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Weapon_mesh_layer_Opaque_vtx_1[3];
extern Gfx gWereCit_Weapon_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Tip_mesh_layer_Opaque_vtx_0[15];
extern Gfx gWereCit_Tip_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Hip_mesh_layer_Opaque_vtx_0[19];
extern Gfx gWereCit_Hip_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Hip_mesh_layer_Opaque_vtx_1[3];
extern Gfx gWereCit_Hip_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Leg_L_mesh_layer_Opaque_vtx_0[15];
extern Gfx gWereCit_Leg_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Leg_L_mesh_layer_Opaque_vtx_1[7];
extern Gfx gWereCit_Leg_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Shin_L_mesh_layer_Opaque_vtx_0[12];
extern Gfx gWereCit_Shin_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Shin_L_mesh_layer_Opaque_vtx_1[4];
extern Gfx gWereCit_Shin_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Foot_L_mesh_layer_Opaque_vtx_0[32];
extern Gfx gWereCit_Foot_L_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Foot_L_mesh_layer_Opaque_vtx_1[12];
extern Gfx gWereCit_Foot_L_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Foot_L_mesh_layer_Opaque_vtx_2[8];
extern Gfx gWereCit_Foot_L_mesh_layer_Opaque_tri_2[];
extern Vtx gWereCit_Leg_R_mesh_layer_Opaque_vtx_0[18];
extern Gfx gWereCit_Leg_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Leg_R_mesh_layer_Opaque_vtx_1[7];
extern Gfx gWereCit_Leg_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Shin_R_mesh_layer_Opaque_vtx_0[12];
extern Gfx gWereCit_Shin_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Shin_R_mesh_layer_Opaque_vtx_1[4];
extern Gfx gWereCit_Shin_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Foot_R_mesh_layer_Opaque_vtx_0[8];
extern Gfx gWereCit_Foot_R_mesh_layer_Opaque_tri_0[];
extern Vtx gWereCit_Foot_R_mesh_layer_Opaque_vtx_1[35];
extern Gfx gWereCit_Foot_R_mesh_layer_Opaque_tri_1[];
extern Vtx gWereCit_Foot_R_mesh_layer_Opaque_vtx_2[12];
extern Gfx gWereCit_Foot_R_mesh_layer_Opaque_tri_2[];
extern Gfx mat_gWereCit_f3dlite_material_038_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_039_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_032_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_007_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_033_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_034_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_036_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_035_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_009_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_010_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_013_layerOpaque[];
extern Gfx mat_gWereCit_f3dlite_material_012_layerOpaque[];
extern Gfx gWereCit_Chest_mesh_layer_Opaque[];
extern Gfx gWereCit_Head_mesh_layer_Opaque[];
extern Gfx gWereCit_Shoulder_L_mesh_layer_Opaque[];
extern Gfx gWereCit_Shoulder_R_mesh_layer_Opaque[];
extern Gfx gWereCit_Arm_R_mesh_layer_Opaque[];
extern Gfx gWereCit_Hand_R_mesh_layer_Opaque[];
extern Gfx gWereCit_Weapon_mesh_layer_Opaque[];
extern Gfx gWereCit_Tip_mesh_layer_Opaque[];
extern Gfx gWereCit_Hip_mesh_layer_Opaque[];
extern Gfx gWereCit_Leg_L_mesh_layer_Opaque[];
extern Gfx gWereCit_Shin_L_mesh_layer_Opaque[];
extern Gfx gWereCit_Foot_L_mesh_layer_Opaque[];
extern Gfx gWereCit_Leg_R_mesh_layer_Opaque[];
extern Gfx gWereCit_Shin_R_mesh_layer_Opaque[];
extern Gfx gWereCit_Foot_R_mesh_layer_Opaque[];
extern FlexSkeletonHeader gWereCit;
#define GWERECIT_ROOT_POS_LIMB 0
#define GWERECIT_ROOT_ROT_LIMB 1
#define GWERECIT_CHEST_LIMB 2
#define GWERECIT_HEAD_LIMB 3
#define GWERECIT_SHOULDER_L_LIMB 4
#define GWERECIT_SHOULDER_R_LIMB 5
#define GWERECIT_ARM_R_LIMB 6
#define GWERECIT_HAND_R_LIMB 7
#define GWERECIT_WEAPON_LIMB 8
#define GWERECIT_TIP_LIMB 9
#define GWERECIT_HIP_LIMB 10
#define GWERECIT_LEG_L_LIMB 11
#define GWERECIT_SHIN_L_LIMB 12
#define GWERECIT_FOOT_L_LIMB 13
#define GWERECIT_LEG_R_LIMB 14
#define GWERECIT_SHIN_R_LIMB 15
#define GWERECIT_FOOT_R_LIMB 16
#define GWERECIT_NUM_LIMBS 17
