extern u64 gGateskel_CASTLEVANIA2_E6394392_2_0_C4196221_ciByRGBA_ci4[];
extern u64 gGateskel_CASTLEVANIA2_E6394392_2_0_C4196221_ciByRGBA_pal_rgba16[];
extern u64 gGateskel_CASTLEVANIA2_103AF0E9_2_0_1DB5477D_ciByRGBA_ci4[];
extern u64 gGateskel_CASTLEVANIA2_103AF0E9_2_0_1DB5477D_ciByRGBA_pal_rgba16[];
extern Vtx gGateskel_DoorL_mesh_layer_Opaque_vtx_0[8];
extern Gfx gGateskel_DoorL_mesh_layer_Opaque_tri_0[];
extern Vtx gGateskel_DoorL_mesh_layer_Opaque_vtx_1[4];
extern Gfx gGateskel_DoorL_mesh_layer_Opaque_tri_1[];
extern Vtx gGateskel_DoorR_mesh_layer_Opaque_vtx_0[8];
extern Gfx gGateskel_DoorR_mesh_layer_Opaque_tri_0[];
extern Vtx gGateskel_DoorR_mesh_layer_Opaque_vtx_1[4];
extern Gfx gGateskel_DoorR_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gGateskel_GateWood_layerOpaque[];
extern Gfx mat_gGateskel_WoodGrain_layerOpaque[];
extern Gfx gGateskel_DoorL_mesh_layer_Opaque[];
extern Gfx gGateskel_DoorR_mesh_layer_Opaque[];
extern SkeletonHeader gGateskel;
#define GGATESKEL_ROOT_POS_LIMB 0
#define GGATESKEL_ROOT_ROT_LIMB 1
#define GGATESKEL_DOORL_LIMB 2
#define GGATESKEL_DOORR_LIMB 3
#define GGATESKEL_NUM_LIMBS 4
